_target_: src.models.sign_module.ASLModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.aman_transformer_v2.Transformer
  _recursive_: True
  num_blocks: 2
  mlp_ratio : 2
  mlp_dropout_ratio : 0.3
  units: 384
  num_classes: 250
  input_size : 32
