_target_: src.models.asl_sign_module.ASLModule

optimizer:
  opt_name: lookahead_RAdam
  weight_decay: 1e-6
  learning_rate: 1e-4

scheduler: 
  sch_name: CosineAnnealingLR
  eta_min: 1e-6
  max_epochs: 200



net:
  _target_: src.models.components.transformer.Net
  num_blocks: 1
  num_classes: 250
  num_head: 4
  embed_dim: 512
  max_length: 60 
  num_point: 82


