_target_: src.models.sign_module.ASLModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  name : CosineAnnealingLR
  mode: min
  factor: 0.1
  patience: 10
  max_epochs : ${trainer.max_epochs}
  eta_min : 1e-6

net:
  _target_: src.models.components.margin_net.ASLLinearModel
  _recursive_: True
  in_features: 472
  first_out_features: 1024
  num_classes: 250
  num_blocks: 3
  drop_rate: 0.4
