_target_: src.models.sign_module.ASLModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.margin_net.ASLLinearModel
  in_features: 3258
  first_out_features: 2048
  num_classes: 250
  num_blocks: 5
  drop_rate: 0.4
