defaults:
  - total_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

Acc_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_{val_acc:.2f}_{val_loss:.4f}"
  save_top_k: 1
  monitor: "val_acc"
  mode: "max"
  save_last: False
  auto_insert_metric_name: False
  save_weights_only: True

Loss_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_{val_acc:.2f}_{val_loss:.4f}"
  save_top_k: 1
  monitor: "val_loss"
  mode: "min"
  save_last: False
  auto_insert_metric_name: False
  save_weights_only: True
  
early_stopping:
  monitor: "val_acc"
  patience: 20
  mode: "max"

model_summary:
  max_depth: -1
