model_checkpoint_acc:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_acc_{val_acc:.3f}"
  monitor: "val_acc"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False
  save_weights_only : True
  save_top_k: 3

model_checkpoint_f1:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_f1_{val_f1:.3f}"
  monitor: "val_f1"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False
  save_weights_only : True
  save_top_k: 3